using System.Collections.Generic;

namespace SuperQAT
{
    /// <summary>
    /// Complete list of MSO control IDs that can be executed via
    /// CommandBars.ExecuteMso(). These are the same commands available
    /// in File > Options > Quick Access Toolbar > All Commands.
    /// </summary>
    public static class MsoCommands
    {
        /// <summary>
        /// Returns all commands as (DisplayName, MsoId) pairs, sorted alphabetically.
        /// </summary>
        public static List<(string Name, string MsoId)> GetAll()
        {
            return new List<(string, string)>
            {
                ("About", "ApplicationOptionsDialog"),
                ("Accept All Changes in Document", "ReviewAcceptAllChangesInDoc"),
                ("Accept and Move to Next", "ReviewAcceptChange"),
                ("Accessibility Checker", "AccessibilityChecker"),
                ("Add Chart Element", "ChartAddElement"),
                ("Add Horizontal Line", "HorizontalLineInsert"),
                ("Add Shape", "ShapeInsert"),
                ("Add Text (Table of Contents)", "ReferenceAddText"),
                ("Adjust List Indents", "IndentClassic"),
                ("Align Bottom Center", "AlignBottomCenter"),
                ("Align Bottom Left", "AlignBottomLeft"),
                ("Align Bottom Right", "AlignBottomRight"),
                ("Align Center", "AlignCenter"),
                ("Align Left", "AlignLeft"),
                ("Align Middle Center", "AlignMiddleCenter"),
                ("Align Middle Left", "AlignMiddleLeft"),
                ("Align Middle Right", "AlignMiddleRight"),
                ("Align Right", "AlignRight"),
                ("Align Top Center", "AlignTopCenter"),
                ("Align Top Left", "AlignTopLeft"),
                ("Align Top Right", "AlignTopRight"),
                ("All Caps", "AllCaps"),
                ("Arrange All Windows", "WindowsArrangeAll"),
                ("AutoCorrect Options", "AutoCorrectOptions"),
                ("AutoFit Contents", "TableAutoFitContent"),
                ("AutoFit Window", "TableAutoFitWindow"),
                ("AutoFormat", "AutoFormat"),
                ("AutoSave", "FileSave"),
                ("AutoText", "AutoTextInsert"),
                ("Blank Page", "PageBreakInsertOrRemove"),
                ("Bold", "Bold"),
                ("Bookmark", "BookmarkInsert"),
                ("Borders and Shading", "BordersAndShadingDialog"),
                ("Borders: Bottom", "BorderBottom"),
                ("Borders: Left", "BorderLeft"),
                ("Borders: None", "BorderNone"),
                ("Borders: Outside", "BorderOutside"),
                ("Borders: Right", "BorderRight"),
                ("Borders: Top", "BorderTop"),
                ("Bring Forward", "ObjectBringForward"),
                ("Bring in Front of Text", "ObjectBringInFrontOfText"),
                ("Bring to Front", "ObjectBringToFront"),
                ("Building Blocks Organizer", "OrganizerBuildingBlocks"),
                ("Bullets", "Bullets"),
                ("Capitalize Each Word", "ChangeCase"),
                ("Caption: Insert", "CaptionInsert"),
                ("Cell Margins", "TableCellCustomMargins"),
                ("Change Case", "ChangeCase"),
                ("Change Chart Type", "ChartTypeChange"),
                ("Change Picture", "PictureChange"),
                ("Change Shape", "ShapeChange"),
                ("Character Spacing", "FontSpacing"),
                ("Chart: Area", "ChartTypeArea"),
                ("Chart: Bar", "ChartTypeBar"),
                ("Chart: Column", "ChartTypeColumn"),
                ("Chart: Line", "ChartTypeLine"),
                ("Chart: Pie", "ChartTypePie"),
                ("Check Compatibility", "CompatibilityChecker"),
                ("Clear All Formatting", "ClearFormatting"),
                ("Clear Table", "TableClear"),
                ("Clipboard Pane", "PasteSpecialDialog"),
                ("Close", "FileClose"),
                ("Close All", "FileCloseAll"),
                ("Close Header and Footer", "HeaderFooterClose"),
                ("Collapse All", "OutlineCollapseAll"),
                ("Color: Blue", "FontColorPicker"),
                ("Color: Green", "FontColorPicker"),
                ("Color: Red", "FontColorPicker"),
                ("Columns: More", "PageLayoutColumnsGallery"),
                ("Columns: One", "ColumnsOne"),
                ("Columns: Three", "ColumnsThree"),
                ("Columns: Two", "ColumnsTwo"),
                ("Combine Documents", "MergeDocuments"),
                ("Compare Documents", "CompareDocuments"),
                ("Compress Pictures", "PicturesCompress"),
                ("Content Control: Check Box", "ContentControlCheckBox"),
                ("Content Control: Combo Box", "ContentControlComboBox"),
                ("Content Control: Date Picker", "ContentControlDatePicker"),
                ("Content Control: Drop-Down", "ContentControlDropdownList"),
                ("Content Control: Picture", "ContentControlPicture"),
                ("Content Control: Plain Text", "ContentControlText"),
                ("Content Control: Repeating Section", "ContentControlRepeatingSection"),
                ("Content Control: Rich Text", "ContentControlRichText"),
                ("Convert Table to Text", "TableConvertToText"),
                ("Convert Text to Table", "ConvertTextToTable"),
                ("Copy", "Copy"),
                ("Cover Page", "CoverPageInsertGallery"),
                ("Cross-reference", "CrossReferenceInsert"),
                ("Custom Margins", "PageMarginsGallery"),
                ("Customize Keyboard", "CustomizeKeyboardShortcuts"),
                ("Customize Quick Access Toolbar", "ToolbarCustomize"),
                ("Customize Ribbon", "TabHomeWord"),
                ("Cut", "Cut"),
                ("Date and Time", "DateAndTimeInsert"),
                ("Decrease Font Size", "ShrinkFont"),
                ("Decrease Indent", "IndentDecrement"),
                ("Define New Bullet", "BulletDefine"),
                ("Define New Multilevel List", "MultilevelListDefine"),
                ("Define New Number Format", "NumberFormatDefine"),
                ("Delete All Comments", "ReviewDeleteAllComments"),
                ("Delete Cells", "TableDeleteCells"),
                ("Delete Columns", "TableDeleteColumns"),
                ("Delete Comment", "ReviewDeleteComment"),
                ("Delete Rows", "TableDeleteRows"),
                ("Delete Table", "TableDelete"),
                ("Design Mode", "DesignMode"),
                ("Different First Page", "HeaderFooterDifferentFirstPage"),
                ("Different Odd & Even Pages", "HeaderFooterDifferentOddEvenPages"),
                ("Distribute Columns", "TableColumnsDistribute"),
                ("Distribute Rows", "TableRowsDistribute"),
                ("Document Inspector", "InspectDocument"),
                ("Document Protection", "ReviewRestrictFormatting"),
                ("Double Strikethrough", "DoubleStrikethrough"),
                ("Double Underline", "UnderlineDouble"),
                ("Draft View", "ViewDraft"),
                ("Draw Table", "TableDraw"),
                ("Drop Cap: Dropped", "DropCapDropped"),
                ("Drop Cap: In Margin", "DropCapMargin"),
                ("Drop Cap: None", "DropCapNone"),
                ("Edit Footer", "FooterEditFooter"),
                ("Edit Header", "HeaderEditHeader"),
                ("Editor / Spelling", "Spelling"),
                ("Effects (Theme)", "ThemeEffects"),
                ("Encrypt with Password", "FileEncrypt"),
                ("Endnote: Insert", "FootnoteEndnoteInsert"),
                ("Envelopes", "EnvelopesAndLabelsDialog"),
                ("Equation", "EquationInsertGallery"),
                ("Eraser (Table)", "TableEraser"),
                ("Expand All", "OutlineExpandAll"),
                ("Export to PDF/XPS", "FileSaveAsPdfOrXps"),
                ("Field", "QuickPartsFieldInsert"),
                ("Field Codes: Toggle", "ViewFieldCodes"),
                ("Find", "Find"),
                ("Find and Replace", "FindAndReplace"),
                ("Flip Horizontal", "ObjectFlipHorizontal"),
                ("Flip Vertical", "ObjectFlipVertical"),
                ("Focus Mode", "ViewFocusMode"),
                ("Font Color", "FontColorPicker"),
                ("Font Dialog", "FontDialog"),
                ("Font Size: Decrease", "ShrinkFont"),
                ("Font Size: Increase", "GrowFont"),
                ("Footer", "FooterInsertGallery"),
                ("Footnote: Insert", "FootnoteInsert"),
                ("Format Painter", "FormatPainter"),
                ("Formatting Marks", "ShowHide"),
                ("Go To", "GoTo"),
                ("Gridlines", "ViewGridlines"),
                ("Group Objects", "ObjectsGroup"),
                ("Grow Font", "GrowFont"),
                ("Header", "HeaderInsertGallery"),
                ("Heading 1", "StyleHeading1"),
                ("Heading 2", "StyleHeading2"),
                ("Heading 3", "StyleHeading3"),
                ("Heading 4", "StyleHeading4"),
                ("Heading 5", "StyleHeading5"),
                ("Help", "Help"),
                ("Hidden Text", "Hidden"),
                ("Highlight", "TextHighlightColorPicker"),
                ("Horizontal Line", "HorizontalLineInsert"),
                ("Hyperlink", "HyperlinkInsert"),
                ("Hyphenation: Automatic", "HyphenationAutomatic"),
                ("Hyphenation: Manual", "HyphenationManual"),
                ("Hyphenation: None", "HyphenationNone"),
                ("Icons", "IconsInsert"),
                ("Immersive Reader", "ViewImmersiveReader"),
                ("Increase Font Size", "GrowFont"),
                ("Increase Indent", "IndentIncrement"),
                ("Index: Insert", "IndexInsert"),
                ("Index: Mark Entry", "IndexMarkEntry"),
                ("Index: Update", "IndexUpdate"),
                ("Insert Address Block", "MailMergeAddressBlockInsert"),
                ("Insert Caption", "CaptionInsert"),
                ("Insert Cells", "TableInsertCells"),
                ("Insert Citation", "CitationInsert"),
                ("Insert Columns Left", "TableInsertColumnsLeft"),
                ("Insert Columns Right", "TableInsertColumnsRight"),
                ("Insert Comment", "ReviewNewComment"),
                ("Insert Date", "DateAndTimeInsert"),
                ("Insert Endnote", "FootnoteEndnoteInsert"),
                ("Insert Equation", "EquationInsertNew"),
                ("Insert Field", "QuickPartsFieldInsert"),
                ("Insert Footnote", "FootnoteInsert"),
                ("Insert Frame", "FrameInsert"),
                ("Insert Merge Field", "MailMergeMergeFieldInsert"),
                ("Insert Online Pictures", "PictureInsertFromOnline"),
                ("Insert Online Video", "VideoInsertFromOnline"),
                ("Insert Page Number", "PageNumberInsertGallery"),
                ("Insert Picture", "PictureInsertFromFile"),
                ("Insert Rows Above", "TableInsertRowsAbove"),
                ("Insert Rows Below", "TableInsertRowsBelow"),
                ("Insert Signature Line", "SignatureLineInsert"),
                ("Insert Symbol", "SymbolInsert"),
                ("Insert Table", "TableInsertGallery"),
                ("Insert Table of Authorities", "TableOfAuthoritiesInsert"),
                ("Insert Table of Contents", "TableOfContentsInsert"),
                ("Insert Table of Figures", "TableOfFiguresInsert"),
                ("Insert Text Box", "TextBoxInsert"),
                ("Insert Time", "DateAndTimeInsert"),
                ("Insert WordArt", "WordArtInsert"),
                ("Italic", "Italic"),
                ("Justify", "ParagraphJustify"),
                ("Keep Lines Together", "KeepLinesTogether"),
                ("Keep with Next", "KeepWithNext"),
                ("Labels", "LabelsDialog"),
                ("Landscape Orientation", "PageOrientationLandscape"),
                ("Language: Set Proofing", "SetLanguage"),
                ("Language: Translate Document", "TranslateDocument"),
                ("Language: Translate Selection", "TranslateSelected"),
                ("Last Column (Table Style)", "TableStyleLastColumn"),
                ("Line Numbers", "PageLayoutLineNumbers"),
                ("Line Spacing", "ParagraphSpacing"),
                ("Link to Previous", "HeaderFooterLinkToPrevious"),
                ("Lock Tracking", "ReviewTrackChangesLock"),
                ("Macros: Record", "MacroRecord"),
                ("Macros: View", "ViewMacros"),
                ("Mail Merge: Finish & Merge", "MailMergeFinishAndMerge"),
                ("Mail Merge: Preview Results", "MailMergePreviewResults"),
                ("Mail Merge: Select Recipients", "MailMergeSelectRecipients"),
                ("Mail Merge: Start", "MailMergeStartMailMerge"),
                ("Manage Sources", "ManageSources"),
                ("Manage Styles", "ManageStyles"),
                ("Margins: Mirrored", "PageMarginsGallery"),
                ("Margins: Moderate", "PageMarginModerate"),
                ("Margins: Narrow", "PageMarginNarrow"),
                ("Margins: Normal", "PageMarginNormal"),
                ("Margins: Wide", "PageMarginWide"),
                ("Mark Citation", "TableOfAuthoritiesMarkCitation"),
                ("Mark Index Entry", "IndexMarkEntry"),
                ("Merge Cells", "TableMergeCells"),
                ("Modify Style", "ModifyStyle"),
                ("Multilevel List", "MultilevelListGallery"),
                ("Navigation Pane", "NavigationPaneFind"),
                ("New Blank Document", "FileNew"),
                ("New Comment", "ReviewNewComment"),
                ("New Window", "WindowNew"),
                ("Next Change", "ReviewNextChange"),
                ("Next Comment", "ReviewNextComment"),
                ("Next Footnote", "FootnoteNextFootnote"),
                ("No Spacing Style", "StyleNoSpacing"),
                ("Normal Style", "StyleNormal"),
                ("Numbering", "Numbering"),
                ("Object: Insert", "OleObjectInsert"),
                ("Open", "FileOpen"),
                ("Orientation: Landscape", "PageOrientationLandscape"),
                ("Orientation: Portrait", "PageOrientationPortrait"),
                ("Outline View", "ViewOutline"),
                ("Page Background: Watermark", "WatermarkGallery"),
                ("Page Border", "PageBorderAndShadingDialog"),
                ("Page Break", "PageBreakInsertOrRemove"),
                ("Page Color", "PageColorPicker"),
                ("Page Number: Bottom of Page", "PageNumbersBottom"),
                ("Page Number: Current Position", "PageNumbersCurrent"),
                ("Page Number: Format", "PageNumberFormat"),
                ("Page Number: Remove", "PageNumbersRemove"),
                ("Page Number: Top of Page", "PageNumbersTop"),
                ("Page Setup Dialog", "PageSetupDialog"),
                ("Paragraph Dialog", "ParagraphDialog"),
                ("Paragraph Shading", "ShadingColorPicker"),
                ("Paste", "Paste"),
                ("Paste Special", "PasteSpecialDialog"),
                ("Paste: Keep Source Formatting", "PasteSourceFormatting"),
                ("Paste: Keep Text Only", "PasteTextOnly"),
                ("Paste: Merge Formatting", "PasteDestinationFormatting"),
                ("Picture Border", "PictureBorderColorPicker"),
                ("Picture Crop", "PictureCrop"),
                ("Picture Effects", "PictureEffectsMenu"),
                ("Picture Layout", "PictureLayoutGallery"),
                ("Picture Reset", "PictureReset"),
                ("Picture Styles", "PictureStylesGallery"),
                ("Portrait Orientation", "PageOrientationPortrait"),
                ("Position Object", "ObjectPosition"),
                ("Previous Change", "ReviewPreviousChange"),
                ("Previous Comment", "ReviewPreviousComment"),
                ("Print", "FilePrint"),
                ("Print Layout View", "ViewPrintLayout"),
                ("Print Preview", "FilePrintPreview"),
                ("Protect Document", "ReviewProtectDocument"),
                ("Quick Parts", "QuickPartsInsertGallery"),
                ("Quick Print", "FilePrintQuick"),
                ("Quick Styles", "StyleGalleryClassic"),
                ("Quick Tables", "QuickTablesInsertGallery"),
                ("Read Mode", "ViewReadMode"),
                ("Redo", "Redo"),
                ("Reject All Changes", "ReviewRejectAllChangesInDoc"),
                ("Reject and Move to Next", "ReviewRejectChange"),
                ("Remove All Formatting", "ClearFormatting"),
                ("Remove Hyperlink", "HyperlinkRemove"),
                ("Remove Table of Contents", "TableOfContentsRemove"),
                ("Remove Watermark", "WatermarkRemove"),
                ("Repeat", "Redo"),
                ("Repeat Header Rows", "TableHeaderRows"),
                ("Replace", "Replace"),
                ("Research", "Research"),
                ("Restrict Editing", "ReviewRestrictFormatting"),
                ("Reviewing Pane: Horizontal", "ReviewingPaneHorizontal"),
                ("Reviewing Pane: Vertical", "ReviewingPaneVertical"),
                ("Rotate Left 90", "ObjectRotateLeft90"),
                ("Rotate Right 90", "ObjectRotateRight90"),
                ("Ruler", "ViewRuler"),
                ("Save", "FileSave"),
                ("Save As", "FileSaveAs"),
                ("Save As PDF", "FileSaveAsPdfOrXps"),
                ("Screenshot", "ScreenClipping"),
                ("Screen Clipping", "ScreenClipping"),
                ("Section Break: Continuous", "SectionBreakContinuous"),
                ("Section Break: Even Page", "SectionBreakEvenPage"),
                ("Section Break: Next Page", "SectionBreakNextPage"),
                ("Section Break: Odd Page", "SectionBreakOddPage"),
                ("Select All", "SelectAll"),
                ("Select Cell", "TableSelectCell"),
                ("Select Column", "TableSelectColumn"),
                ("Select Objects", "SelectionPane"),
                ("Select Row", "TableSelectRow"),
                ("Select Table", "TableSelect"),
                ("Selection Pane", "SelectionPane"),
                ("Send Backward", "ObjectSendBackward"),
                ("Send Behind Text", "ObjectSendBehindText"),
                ("Send to Back", "ObjectSendToBack"),
                ("Shading", "ShadingColorPicker"),
                ("Shape Effects", "ShapeEffectsMenu"),
                ("Shape Fill", "ShapeFillColorPicker"),
                ("Shape Outline", "ShapeOutlineColorPicker"),
                ("Shapes: Insert", "ShapesInsertGallery"),
                ("Share", "FileShare"),
                ("Show All Formatting Marks", "ShowHide"),
                ("Show Comments", "ReviewShowComments"),
                ("Show Markup", "ReviewShowMarkup"),
                ("Shrink Font", "ShrinkFont"),
                ("Shrink One Page", "ShrinkOnePage"),
                ("Simple Markup", "ReviewSimpleMarkup"),
                ("Size: A4", "PageSizeA4"),
                ("Size: A5", "PageSizeA5"),
                ("Size: Letter", "PageSizeLetter"),
                ("Size: Legal", "PageSizeLegal"),
                ("Small Caps", "SmallCaps"),
                ("SmartArt", "SmartArtInsert"),
                ("Snap to Grid", "SnapToGrid"),
                ("Sort", "SortDialog"),
                ("Spelling and Grammar", "Spelling"),
                ("Split Cells", "TableSplitCells"),
                ("Split Table", "TableSplit"),
                ("Split Window", "WindowSplit"),
                ("Start Mail Merge", "MailMergeStartMailMerge"),
                ("Strikethrough", "Strikethrough"),
                ("Style: Book Title", "StyleBookTitle"),
                ("Style: Emphasis", "StyleEmphasis"),
                ("Style: Heading 1", "StyleHeading1"),
                ("Style: Heading 2", "StyleHeading2"),
                ("Style: Heading 3", "StyleHeading3"),
                ("Style: Intense Emphasis", "StyleIntenseEmphasis"),
                ("Style: Intense Quote", "StyleIntenseQuote"),
                ("Style: Intense Reference", "StyleIntenseReference"),
                ("Style: List Paragraph", "StyleListParagraph"),
                ("Style: No Spacing", "StyleNoSpacing"),
                ("Style: Normal", "StyleNormal"),
                ("Style: Quote", "StyleQuote"),
                ("Style: Strong", "StyleStrong"),
                ("Style: Subtitle", "StyleSubtitle"),
                ("Style: Subtle Emphasis", "StyleSubtleEmphasis"),
                ("Style: Subtle Reference", "StyleSubtleReference"),
                ("Style: Title", "StyleTitle"),
                ("Subscript", "Subscript"),
                ("Superscript", "Superscript"),
                ("Switch Windows", "WindowSwitchWindows"),
                ("Symbol: Insert", "SymbolInsert"),
                ("Table of Authorities: Insert", "TableOfAuthoritiesInsert"),
                ("Table of Contents: Insert", "TableOfContentsInsert"),
                ("Table of Contents: Remove", "TableOfContentsRemove"),
                ("Table of Contents: Update", "TableOfContentsUpdate"),
                ("Table of Figures: Insert", "TableOfFiguresInsert"),
                ("Table of Figures: Update", "TableOfFiguresUpdate"),
                ("Table Properties", "TableProperties"),
                ("Text Box: Draw", "TextBoxDrawMenu"),
                ("Text Direction", "TextDirection"),
                ("Text Effects", "TextEffectsMenu"),
                ("Text Highlight Color", "TextHighlightColorPicker"),
                ("Text Wrapping: Behind", "ObjectBehindText"),
                ("Text Wrapping: In Front", "ObjectInFrontOfText"),
                ("Text Wrapping: In Line", "ObjectInLineWithText"),
                ("Text Wrapping: Square", "ObjectWrapSquare"),
                ("Text Wrapping: Through", "ObjectWrapThrough"),
                ("Text Wrapping: Tight", "ObjectWrapTight"),
                ("Text Wrapping: Top and Bottom", "ObjectWrapTopAndBottom"),
                ("Theme Colors", "ThemeColors"),
                ("Theme Fonts", "ThemeFonts"),
                ("Themes", "ThemesGallery"),
                ("Thesaurus", "Thesaurus"),
                ("Track Changes", "ReviewTrackChanges"),
                ("Track Changes Options", "ReviewTrackChangesOptions"),
                ("Translate Document", "TranslateDocument"),
                ("Translate Selection", "TranslateSelected"),
                ("Underline", "Underline"),
                ("Underline: Dashed", "UnderlineDash"),
                ("Underline: Dotted", "UnderlineDotted"),
                ("Underline: Double", "UnderlineDouble"),
                ("Underline: Thick", "UnderlineThick"),
                ("Underline: Wavy", "UnderlineWavy"),
                ("Underline: Word Only", "UnderlineWords"),
                ("Undo", "Undo"),
                ("Ungroup Objects", "ObjectsUngroup"),
                ("Update All Fields", "UpdateFields"),
                ("Update Index", "IndexUpdate"),
                ("Update Table of Contents", "TableOfContentsUpdate"),
                ("Update Table of Figures", "TableOfFiguresUpdate"),
                ("View Gridlines (Table)", "TableShowGridlines"),
                ("View Macros", "ViewMacros"),
                ("View Ruler", "ViewRuler"),
                ("View Side by Side", "ViewSideBySide"),
                ("Visual Basic Editor", "VisualBasic"),
                ("Watermark: Custom", "WatermarkCustomDialog"),
                ("Watermark: Remove", "WatermarkRemove"),
                ("Web Layout View", "ViewWeb"),
                ("Widow/Orphan Control", "WidowOrphanControl"),
                ("Word Count", "WordCount"),
                ("WordArt: Insert", "WordArtInsert"),
                ("XML Mapping Pane", "XMLMappingPane"),
                ("Zoom: 100%", "Zoom100"),
                ("Zoom: One Page", "ZoomOnePage"),
                ("Zoom: Page Width", "ZoomPageWidth"),
                ("Zoom: Two Pages", "ZoomTwoPages"),
                ("Zoom Dialog", "ZoomDialog"),
            };
        }
    }
}
