Attribute VB_Name = "SuperQATData"
'==============================================================================
' SuperQAT v3.0.0 - PowerPoint Command Data
' 769 commands from official Microsoft 365 control IDs
'==============================================================================
Option Explicit

Public Function GetAllCommands() As Variant
    Dim result() As Variant
    ReDim result(0 To 768)

    ' Chunk 1 (commands 0-19)
    result(0) = Array("_3DBevelOptionsDialog", "3 D Bevel Options Dialog")
    result(1) = Array("_3DModelPlay", "3 D Model Play")
    result(2) = Array("_3DRotationOptionsDialog", "3 D Rotation Options Dialog")
    result(3) = Array("About", "About")
    result(4) = Array("AccessibilityChecker", "Accessibility Checker")
    result(5) = Array("AccessibilityHelp", "Accessibility Help")
    result(6) = Array("ActionInsert", "Action Insert")
    result(7) = Array("ActivateOffice", "Activate Office")
    result(8) = Array("ActiveXButton", "Active X Button")
    result(9) = Array("ActiveXCheckBox", "Active X Check Box")
    result(10) = Array("ActiveXComboBox", "Active X Combo Box")
    result(11) = Array("ActiveXImage", "Active X Image")
    result(12) = Array("ActiveXLabel", "Active X Label")
    result(13) = Array("ActiveXListBox", "Active X List Box")
    result(14) = Array("ActiveXRadioButton", "Active X Radio Button")
    result(15) = Array("ActiveXScrollBar", "Active X Scroll Bar")
    result(16) = Array("ActiveXSpinButton", "Active X Spin Button")
    result(17) = Array("ActiveXTextBox", "Active X Text Box")
    result(18) = Array("ActiveXToggleButton", "Active X Toggle Button")
    result(19) = Array("AddCameoPlaceholder", "Add Cameo Placeholder")

    ' Chunk 2 (commands 20-39)
    result(20) = Array("AddHorizontalGuide", "Add Horizontal Guide")
    result(21) = Array("AddInManager", "Add In Manager")
    result(22) = Array("AddNode", "Add Node")
    result(23) = Array("AddOffSlideTitle", "Add Off Slide Title")
    result(24) = Array("AddSlideTitle", "Add Slide Title")
    result(25) = Array("AddVerticalGuide", "Add Vertical Guide")
    result(26) = Array("AdvancedFileProperties", "Advanced File Properties")
    result(27) = Array("AdvertisePublishAs", "Advertise Publish As")
    result(28) = Array("AlignDistributeHorizontally", "Align Distribute Horizontally")
    result(29) = Array("AlignDistributeVertically", "Align Distribute Vertically")
    result(30) = Array("AlternativeText", "Alternative Text")
    result(31) = Array("AnimationCustomActionVerbDialog", "Animation Custom Action Verb Dialog")
    result(32) = Array("AnimationCustomAddActionVerbDialog", "Animation Custom Add Action Verb Dialog")
    result(33) = Array("AnimationCustomAddEmphasisDialog", "Animation Custom Add Emphasis Dialog")
    result(34) = Array("AnimationCustomAddEntranceDialog", "Animation Custom Add Entrance Dialog")
    result(35) = Array("AnimationCustomAddExitDialog", "Animation Custom Add Exit Dialog")
    result(36) = Array("AnimationCustomAddPathDialog", "Animation Custom Add Path Dialog")
    result(37) = Array("AnimationCustomEmphasisDialog", "Animation Custom Emphasis Dialog")
    result(38) = Array("AnimationCustomEntranceDialog", "Animation Custom Entrance Dialog")
    result(39) = Array("AnimationCustomExitDialog", "Animation Custom Exit Dialog")

    ' Chunk 3 (commands 40-59)
    result(40) = Array("AnimationCustomPathDialog", "Animation Custom Path Dialog")
    result(41) = Array("AnimationMoveEarlier", "Animation Move Earlier")
    result(42) = Array("AnimationMoveLater", "Animation Move Later")
    result(43) = Array("AnimationPreview", "Animation Preview")
    result(44) = Array("AppGuardTrustPromotion", "App Guard Trust Promotion")
    result(45) = Array("ApplicationOptionsDialog", "Application Options Dialog")
    result(46) = Array("ArrowsMore", "Arrows More")
    result(47) = Array("ArtisticEffectsDialog", "Artistic Effects Dialog")
    result(48) = Array("AudioBookmarkAdd", "Audio Bookmark Add")
    result(49) = Array("AudioBookmarkRemove", "Audio Bookmark Remove")
    result(50) = Array("AudioInsert", "Audio Insert")
    result(51) = Array("AudioToolsTrim", "Audio Tools Trim")
    result(52) = Array("AutoAlternativeText", "Auto Alternative Text")
    result(53) = Array("AutoCorrect", "Auto Correct")
    result(54) = Array("BackgroundRemovalClose", "Background Removal Close")
    result(55) = Array("BarcodeInsert", "Barcode Insert")
    result(56) = Array("BaselineLower", "Baseline Lower")
    result(57) = Array("BaselineRaise", "Baseline Raise")
    result(58) = Array("BookshelfDefine", "Bookshelf Define")
    result(59) = Array("BordersShadingDialog", "Borders Shading Dialog")

    ' Chunk 4 (commands 60-79)
    result(60) = Array("BrightnessLess", "Brightness Less")
    result(61) = Array("BrightnessMore", "Brightness More")
    result(62) = Array("BroadcastEnd", "Broadcast End")
    result(63) = Array("BroadcastFromBeginning", "Broadcast From Beginning")
    result(64) = Array("BroadcastFromCurrent", "Broadcast From Current")
    result(65) = Array("BroadcastNotes", "Broadcast Notes")
    result(66) = Array("BroadcastResume", "Broadcast Resume")
    result(67) = Array("BroadcastSendInvitation", "Broadcast Send Invitation")
    result(68) = Array("BroadcastSlideShow", "Broadcast Slide Show")
    result(69) = Array("BroadcastSlideShowBackstage", "Broadcast Slide Show Backstage")
    result(70) = Array("BroadcastSlideShowGeneric", "Broadcast Slide Show Generic")
    result(71) = Array("BroadcastSlideShowLync", "Broadcast Slide Show Lync")
    result(72) = Array("BroadcastSlideShowOfficeHosted", "Broadcast Slide Show Office Hosted")
    result(73) = Array("BulletsAndNumberingBulletsDialog", "Bullets And Numbering Bullets Dialog")
    result(74) = Array("BulletsAndNumberingNumberingDialog", "Bullets And Numbering Numbering Dialog")
    result(75) = Array("ButtonOpenBrowse", "Button Open Browse")
    result(76) = Array("CameoEnablePreview", "Cameo Enable Preview")
    result(77) = Array("CDAudioPlayTrack", "CD Audio Play Track")
    result(78) = Array("ChangeCaseToggle", "Change Case Toggle")
    result(79) = Array("ChangeIcon", "Change Icon")

    ' Chunk 5 (commands 80-99)
    result(80) = Array("ChangeImage", "Change Image")
    result(81) = Array("CharacterFormattingReset", "Character Formatting Reset")
    result(82) = Array("Chart3DView", "Chart 3 D View")
    result(83) = Array("ChartAddAxis", "Chart Add Axis")
    result(84) = Array("ChartAxesOptionsDialog", "Chart Axes Options Dialog")
    result(85) = Array("ChartAxesTitlesOptionsDialog", "Chart Axes Titles Options Dialog")
    result(86) = Array("ChartCalloutDataLabelAdd", "Chart Callout Data Label Add")
    result(87) = Array("ChartCalloutDataLabelsAdd", "Chart Callout Data Labels Add")
    result(88) = Array("ChartChangeType", "Chart Change Type")
    result(89) = Array("ChartDataLabelAdd", "Chart Data Label Add")
    result(90) = Array("ChartDataLabelDialog", "Chart Data Label Dialog")
    result(91) = Array("ChartDataLabelsAdd", "Chart Data Labels Add")
    result(92) = Array("ChartDataTableOptionsDialog", "Chart Data Table Options Dialog")
    result(93) = Array("ChartDelete", "Chart Delete")
    result(94) = Array("ChartDeleteSeries", "Chart Delete Series")
    result(95) = Array("ChartDepthAxisOptionsDialog", "Chart Depth Axis Options Dialog")
    result(96) = Array("ChartDepthAxisTitleOptionsDialog", "Chart Depth Axis Title Options Dialog")
    result(97) = Array("ChartDepthGridlinesOptionsDialog", "Chart Depth Gridlines Options Dialog")
    result(98) = Array("ChartEditDataSource", "Chart Edit Data Source")
    result(99) = Array("ChartEditText", "Chart Edit Text")

    ' Chunk 6 (commands 100-119)
    result(100) = Array("ChartErrorBarsOptionsDialog", "Chart Error Bars Options Dialog")
    result(101) = Array("ChartExitEditText", "Chart Exit Edit Text")
    result(102) = Array("ChartFloorOptionsDialog", "Chart Floor Options Dialog")
    result(103) = Array("ChartFormatAxis", "Chart Format Axis")
    result(104) = Array("ChartFormatAxisAndSelect", "Chart Format Axis And Select")
    result(105) = Array("ChartFormatAxisTitle", "Chart Format Axis Title")
    result(106) = Array("ChartFormatBackWall", "Chart Format Back Wall")
    result(107) = Array("ChartFormatChartArea", "Chart Format Chart Area")
    result(108) = Array("ChartFormatChartTitle", "Chart Format Chart Title")
    result(109) = Array("ChartFormatDataLabel", "Chart Format Data Label")
    result(110) = Array("ChartFormatDataLabelAndSelect", "Chart Format Data Label And Select")
    result(111) = Array("ChartFormatDataLabels", "Chart Format Data Labels")
    result(112) = Array("ChartFormatDataLabelsAndSelect", "Chart Format Data Labels And Select")
    result(113) = Array("ChartFormatDataPoint", "Chart Format Data Point")
    result(114) = Array("ChartFormatDataPointAndSelect", "Chart Format Data Point And Select")
    result(115) = Array("ChartFormatDataSeries", "Chart Format Data Series")
    result(116) = Array("ChartFormatDataSeriesAndSelect", "Chart Format Data Series And Select")
    result(117) = Array("ChartFormatDataTable", "Chart Format Data Table")
    result(118) = Array("ChartFormatDisplayUnit", "Chart Format Display Unit")
    result(119) = Array("ChartFormatDownBars", "Chart Format Down Bars")

    ' Chunk 7 (commands 120-139)
    result(120) = Array("ChartFormatDropLines", "Chart Format Drop Lines")
    result(121) = Array("ChartFormatErrorBars", "Chart Format Error Bars")
    result(122) = Array("ChartFormatFloor", "Chart Format Floor")
    result(123) = Array("ChartFormatGridlines", "Chart Format Gridlines")
    result(124) = Array("ChartFormatHighLowLine", "Chart Format High Low Line")
    result(125) = Array("ChartFormatLeaderLines", "Chart Format Leader Lines")
    result(126) = Array("ChartFormatLegend", "Chart Format Legend")
    result(127) = Array("ChartFormatLegendEntry", "Chart Format Legend Entry")
    result(128) = Array("ChartFormatMajorGridlinesAndSelect", "Chart Format Major Gridlines And Select")
    result(129) = Array("ChartFormatMinorGridlinesAndSelect", "Chart Format Minor Gridlines And Select")
    result(130) = Array("ChartFormatParetoLine", "Chart Format Pareto Line")
    result(131) = Array("ChartFormatPlotArea", "Chart Format Plot Area")
    result(132) = Array("ChartFormatSelection", "Chart Format Selection")
    result(133) = Array("ChartFormatSeriesLine", "Chart Format Series Line")
    result(134) = Array("ChartFormatSideWall", "Chart Format Side Wall")
    result(135) = Array("ChartFormatTrendline", "Chart Format Trendline")
    result(136) = Array("ChartFormatTrendlineAndSelect", "Chart Format Trendline And Select")
    result(137) = Array("ChartFormatTrendlineLabel", "Chart Format Trendline Label")
    result(138) = Array("ChartFormatUpBars", "Chart Format Up Bars")
    result(139) = Array("ChartFormatWalls", "Chart Format Walls")

    ' Chunk 8 (commands 140-159)
    result(140) = Array("ChartGridlineOptionsDialog", "Chart Gridline Options Dialog")
    result(141) = Array("ChartInsert", "Chart Insert")
    result(142) = Array("ChartInsertDataField", "Chart Insert Data Field")
    result(143) = Array("ChartLegendOptionsDialogDialog", "Chart Legend Options Dialog Dialog")
    result(144) = Array("ChartMajorGridlinesAdd", "Chart Major Gridlines Add")
    result(145) = Array("ChartMinorGridlinesAdd", "Chart Minor Gridlines Add")
    result(146) = Array("ChartPlotAreaOptionsDialog", "Chart Plot Area Options Dialog")
    result(147) = Array("ChartPrimaryHorizontalAxisOptionsDialog", "Chart Primary Horizontal Axis Options Dialog")
    result(148) = Array("ChartPrimaryHorizontalAxisTitleOptionsDialog", "Chart Primary Horizontal Axis Title Options Dialog")
    result(149) = Array("ChartPrimaryHorizontalGridlinesOptionsDialog", "Chart Primary Horizontal Gridlines Options Dialog")
    result(150) = Array("ChartPrimaryVerticalAxisOptionsDialog", "Chart Primary Vertical Axis Options Dialog")
    result(151) = Array("ChartPrimaryVerticalAxisTitleOptionsDialog", "Chart Primary Vertical Axis Title Options Dialog")
    result(152) = Array("ChartPrimaryVerticalGridlinesOptionsDialog", "Chart Primary Vertical Gridlines Options Dialog")
    result(153) = Array("ChartRefresh", "Chart Refresh")
    result(154) = Array("ChartResetToMatchStyle", "Chart Reset To Match Style")
    result(155) = Array("ChartSaveTemplates", "Chart Save Templates")
    result(156) = Array("ChartSecondaryHorizontalAxisOption", "Chart Secondary Horizontal Axis Option")
    result(157) = Array("ChartSecondaryHorizontalAxisTitleOptionsDialog", "Chart Secondary Horizontal Axis Title Options Dialog")
    result(158) = Array("ChartSecondaryHorizontalGridlinesOptionsDialog", "Chart Secondary Horizontal Gridlines Options Dialog")
    result(159) = Array("ChartSecondaryVerticalAxisOptionsDialog", "Chart Secondary Vertical Axis Options Dialog")

    ' Chunk 9 (commands 160-179)
    result(160) = Array("ChartSecondaryVerticalAxisTitleOptionsDialog", "Chart Secondary Vertical Axis Title Options Dialog")
    result(161) = Array("ChartSecondaryVerticalGridlinesOptionsDialog", "Chart Secondary Vertical Gridlines Options Dialog")
    result(162) = Array("ChartSeriesTypeChange", "Chart Series Type Change")
    result(163) = Array("ChartShowData", "Chart Show Data")
    result(164) = Array("ChartShowDataContextualMenu", "Chart Show Data Contextual Menu")
    result(165) = Array("ChartShowDataGrid", "Chart Show Data Grid")
    result(166) = Array("ChartSourceDataContextualMenu", "Chart Source Data Contextual Menu")
    result(167) = Array("ChartSwitchRowColumn", "Chart Switch Row Column")
    result(168) = Array("ChartTitleOptionsDialog", "Chart Title Options Dialog")
    result(169) = Array("ChartTrendlineAdd", "Chart Trendline Add")
    result(170) = Array("ChartTrendlineOptionsDialog", "Chart Trendline Options Dialog")
    result(171) = Array("ChartUpDownBarsOptionsDialog", "Chart Up Down Bars Options Dialog")
    result(172) = Array("ChartWallOptionsDialog", "Chart Wall Options Dialog")
    result(173) = Array("ChartWaterfallSetAsTotal", "Chart Waterfall Set As Total")
    result(174) = Array("ChartWaterfallUnsetTotal", "Chart Waterfall Unset Total")
    result(175) = Array("CheckForUpdates", "Check For Updates")
    result(176) = Array("ChineseTranslationDialog", "Chinese Translation Dialog")
    result(177) = Array("Clear", "Clear")
    result(178) = Array("ClearAllSlidesRecordings", "Clear All Slides Recordings")
    result(179) = Array("ClearCurrentSlideRecording", "Clear Current Slide Recording")

    ' Chunk 10 (commands 180-199)
    result(180) = Array("ClearFormatting", "Clear Formatting")
    result(181) = Array("ClearRecordingOnAllSlides", "Clear Recording On All Slides")
    result(182) = Array("ClearRecordingOnCurrentSlide", "Clear Recording On Current Slide")
    result(183) = Array("ClipArtInsertDialog", "Clip Art Insert Dialog")
    result(184) = Array("CollapseAll", "Collapse All")
    result(185) = Array("ComAddInsDialog", "Com Add Ins Dialog")
    result(186) = Array("ContactUs", "Contact Us")
    result(187) = Array("ContrastLess", "Contrast Less")
    result(188) = Array("ContrastMore", "Contrast More")
    result(189) = Array("ControlProperties", "Control Properties")
    result(190) = Array("ConvertToSmartArtMoreSmartArtGraphicsDialog", "Convert To Smart Art More Smart Art Graphics Dialog")
    result(191) = Array("Copilot", "Copilot")
    result(192) = Array("CopilotDraftSlides", "Copilot Draft Slides")
    result(193) = Array("CopilotInsertPowerpoint", "Copilot Insert Powerpoint")
    result(194) = Array("Copy", "Copy")
    result(195) = Array("CopyCameoAllSlides", "Copy Cameo All Slides")
    result(196) = Array("CreateHandoutsInWord", "Create Handouts In Word")
    result(197) = Array("CustomSlideSize", "Custom Slide Size")
    result(198) = Array("Cut", "Cut")
    result(199) = Array("DateAndTimeInsert", "Date And Time Insert")

    ' Chunk 11 (commands 200-219)
    result(200) = Array("DeleteNode", "Delete Node")
    result(201) = Array("DeleteSegment", "Delete Segment")
    result(202) = Array("DeleteSlideContextual", "Delete Slide Contextual")
    result(203) = Array("DictateInMenu", "Dictate In Menu")
    result(204) = Array("DrawingCanvasExpand", "Drawing Canvas Expand")
    result(205) = Array("DrawingCanvasFit", "Drawing Canvas Fit")
    result(206) = Array("DrawingCanvasResize", "Drawing Canvas Resize")
    result(207) = Array("DrawingCanvasScale", "Drawing Canvas Scale")
    result(208) = Array("DuplicateSelectedSlides", "Duplicate Selected Slides")
    result(209) = Array("EditHyperlinkText", "Edit Hyperlink Text")
    result(210) = Array("EditSlideTitle", "Edit Slide Title")
    result(211) = Array("EquationInsertNew", "Equation Insert New")
    result(212) = Array("EquationLinearFormat", "Equation Linear Format")
    result(213) = Array("EquationProfessional", "Equation Professional")
    result(214) = Array("ExcelSpreadsheetInsert", "Excel Spreadsheet Insert")
    result(215) = Array("ExchangeFolder", "Exchange Folder")
    result(216) = Array("ExitEditCurve", "Exit Edit Curve")
    result(217) = Array("ExportToAnimatedGif", "Export To Animated Gif")
    result(218) = Array("ExportToVideo", "Export To Video")
    result(219) = Array("ExportToVideoRecording", "Export To Video Recording")

    ' Chunk 12 (commands 220-239)
    result(220) = Array("ExportVideoRecording", "Export Video Recording")
    result(221) = Array("ExtensibilityExperimentation", "Extensibility Experimentation")
    result(222) = Array("EyedropperFill", "Eyedropper Fill")
    result(223) = Array("EyedropperFillText", "Eyedropper Fill Text")
    result(224) = Array("EyedropperGlow", "Eyedropper Glow")
    result(225) = Array("EyedropperGlowText", "Eyedropper Glow Text")
    result(226) = Array("EyedropperOutline", "Eyedropper Outline")
    result(227) = Array("EyedropperOutlineText", "Eyedropper Outline Text")
    result(228) = Array("EyedropperRecolor", "Eyedropper Recolor")
    result(229) = Array("FifthCorrectionAlternative", "Fifth Correction Alternative")
    result(230) = Array("FileAddDigitalSignature", "File Add Digital Signature")
    result(231) = Array("FileCheckIn", "File Check In")
    result(232) = Array("FileCheckOut", "File Check Out")
    result(233) = Array("FileCheckOutDiscard", "File Check Out Discard")
    result(234) = Array("FileClose", "File Close")
    result(235) = Array("FileCompatibilityCheckerPowerPoint", "File Compatibility Checker Power Point")
    result(236) = Array("FileDiscardCachedChanges", "File Discard Cached Changes")
    result(237) = Array("FileDocumentInspect", "File Document Inspect")
    result(238) = Array("FileEmailAsPdfEmailAttachment", "File Email As Pdf Email Attachment")
    result(239) = Array("FileEmailAsXpsEmailAttachment", "File Email As Xps Email Attachment")

    ' Chunk 13 (commands 240-259)
    result(240) = Array("FileExit", "File Exit")
    result(241) = Array("FileInternetFax", "File Internet Fax")
    result(242) = Array("FileLinksToFiles", "File Links To Files")
    result(243) = Array("FileNew", "File New")
    result(244) = Array("FileNewDefault", "File New Default")
    result(245) = Array("FileOpen", "File Open")
    result(246) = Array("FileOpenRecentFile", "File Open Recent File")
    result(247) = Array("FileOpenUsingBackstage", "File Open Using Backstage")
    result(248) = Array("FilePackageForCD", "File Package For CD")
    result(249) = Array("FilePermissionRestrictAs", "File Permission Restrict As")
    result(250) = Array("FilePermissionView", "File Permission View")
    result(251) = Array("FilePrint", "File Print")
    result(252) = Array("FilePrintQuick", "File Print Quick")
    result(253) = Array("FilePublishSlides", "File Publish Slides")
    result(254) = Array("FileSave", "File Save")
    result(255) = Array("FileSaveACopy", "File Save A Copy")
    result(256) = Array("FileSaveAs", "File Save As")
    result(257) = Array("FileSaveAsOtherFormats", "File Save As Other Formats")
    result(258) = Array("FileSaveAsPdfOrXps", "File Save As Pdf Or Xps")
    result(259) = Array("FileSaveAsPowerPoint97_2003", "File Save As Power Point 97 _ 2003")

    ' Chunk 14 (commands 260-279)
    result(260) = Array("FileSaveAsPowerPointOpenDocumentPresentation", "File Save As Power Point Open Document Presentation")
    result(261) = Array("FileSaveAsPowerPointPpsx", "File Save As Power Point Ppsx")
    result(262) = Array("FileSaveAsPowerPointPptx", "File Save As Power Point Pptx")
    result(263) = Array("FileSaveAsPowerPointSlideShow", "File Save As Power Point Slide Show")
    result(264) = Array("FileSaveToDocumentManagementServer", "File Save To Document Management Server")
    result(265) = Array("FileSendAsAttachment", "File Send As Attachment")
    result(266) = Array("FileStartWorkflow", "File Start Workflow")
    result(267) = Array("FileVersionHistory", "File Version History")
    result(268) = Array("FileWorkflowTasks", "File Workflow Tasks")
    result(269) = Array("FindDialog", "Find Dialog")
    result(270) = Array("FindNext", "Find Next")
    result(271) = Array("FirstCorrectionAlternative", "First Correction Alternative")
    result(272) = Array("FontColorMoreColorsDialogPowerPoint", "Font Color More Colors Dialog Power Point")
    result(273) = Array("FontDialog", "Font Dialog")
    result(274) = Array("FontSizeDecrease", "Font Size Decrease")
    result(275) = Array("FontSizeIncrease", "Font Size Increase")
    result(276) = Array("FontsReplaceFonts", "Fonts Replace Fonts")
    result(277) = Array("FormatDialog3DModel", "Format Dialog 3 D Model")
    result(278) = Array("FourthCorrectionAlternative", "Fourth Correction Alternative")
    result(279) = Array("GenerateAutoAltText", "Generate Auto Alt Text")

    ' Chunk 15 (commands 280-299)
    result(280) = Array("GlowColorMoreColorsDialog", "Glow Color More Colors Dialog")
    result(281) = Array("GlowsMoreOptions", "Glows More Options")
    result(282) = Array("GoToProperty", "Go To Property")
    result(283) = Array("GraphicsFormatDialog", "Graphics Format Dialog")
    result(284) = Array("GridSettings", "Grid Settings")
    result(285) = Array("GroupOfficeInsider", "Group Office Insider")
    result(286) = Array("GroupOfficeInsiderAbout", "Group Office Insider About")
    result(287) = Array("GroupOfficeInsiderChannel", "Group Office Insider Channel")
    result(288) = Array("GroupOfficeInsiderHelp", "Group Office Insider Help")
    result(289) = Array("GroupOfficeInsiderRegistration", "Group Office Insider Registration")
    result(290) = Array("GuideDelete", "Guide Delete")
    result(291) = Array("HangulHanjaConversionPowerPoint", "Hangul Hanja Conversion Power Point")
    result(292) = Array("HeaderFooterInsert", "Header Footer Insert")
    result(293) = Array("Help", "Help")
    result(294) = Array("HideSlide", "Hide Slide")
    result(295) = Array("HighlightingStop", "Highlighting Stop")
    result(296) = Array("HistoryTab", "History Tab")
    result(297) = Array("HyperlinkCopy", "Hyperlink Copy")
    result(298) = Array("HyperlinkEdit", "Hyperlink Edit")
    result(299) = Array("HyperlinkInsert", "Hyperlink Insert")

    ' Chunk 16 (commands 300-319)
    result(300) = Array("HyperlinkInsertPowerPoint", "Hyperlink Insert Power Point")
    result(301) = Array("HyperlinkOpen", "Hyperlink Open")
    result(302) = Array("HyperlinkOpenInNative", "Hyperlink Open In Native")
    result(303) = Array("HyperlinkOpenInWeb", "Hyperlink Open In Web")
    result(304) = Array("HyperlinkRemove", "Hyperlink Remove")
    result(305) = Array("IconInsertFromFile", "Icon Insert From File")
    result(306) = Array("ImagePlay", "Image Play")
    result(307) = Array("ImeReconvert", "Ime Reconvert")
    result(308) = Array("IndentDecrease", "Indent Decrease")
    result(309) = Array("IndentIncrease", "Indent Increase")
    result(310) = Array("InkColorMoreColorsDialog", "Ink Color More Colors Dialog")
    result(311) = Array("InkCopyAsText", "Ink Copy As Text")
    result(312) = Array("InkDeleteAll", "Ink Delete All")
    result(313) = Array("InkDeleteAllOnSlide", "Ink Delete All On Slide")
    result(314) = Array("InkEquation", "Ink Equation")
    result(315) = Array("InkingStart", "Inking Start")
    result(316) = Array("InkStopInkingReadingView", "Ink Stop Inking Reading View")
    result(317) = Array("InkToMathAnalysis", "Ink To Math Analysis")
    result(318) = Array("InkToolsClose", "Ink Tools Close")
    result(319) = Array("InkToShapeAnalysis", "Ink To Shape Analysis")

    ' Chunk 17 (commands 320-339)
    result(320) = Array("InkToTextAnalysis", "Ink To Text Analysis")
    result(321) = Array("Insert3DModelDefault", "Insert 3 D Model Default")
    result(322) = Array("Insert3DModelDefaultPlaceholder", "Insert 3 D Model Default Placeholder")
    result(323) = Array("Insert3DModelFallback", "Insert 3 D Model Fallback")
    result(324) = Array("Insert3DModelFromFile", "Insert 3 D Model From File")
    result(325) = Array("Insert3DModelFromFileConsumer", "Insert 3 D Model From File Consumer")
    result(326) = Array("Insert3DModelFromOnline", "Insert 3 D Model From Online")
    result(327) = Array("Insert3DModelFromOnlineConsumer", "Insert 3 D Model From Online Consumer")
    result(328) = Array("InsertCameo", "Insert Cameo")
    result(329) = Array("InsertCameoAllSlides", "Insert Cameo All Slides")
    result(330) = Array("InsertClosedCaption", "Insert Closed Caption")
    result(331) = Array("InsertHeaderColumn", "Insert Header Column")
    result(332) = Array("InsertHeaderRow", "Insert Header Row")
    result(333) = Array("InsertIconPlaceholder", "Insert Icon Placeholder")
    result(334) = Array("InsertM365Picture", "Insert M 365 Picture")
    result(335) = Array("InsertM365Video", "Insert M 365 Video")
    result(336) = Array("InsertMobilePicture", "Insert Mobile Picture")
    result(337) = Array("InsertMovieDialog", "Insert Movie Dialog")
    result(338) = Array("InsertMSForms", "Insert MS Forms")
    result(339) = Array("InsertNewComment", "Insert New Comment")

    ' Chunk 18 (commands 340-359)
    result(340) = Array("InsertPowerBI", "Insert Power BI")
    result(341) = Array("InsertTab", "Insert Tab")
    result(342) = Array("InsertVideoFromDevice", "Insert Video From Device")
    result(343) = Array("Insights", "Insights")
    result(344) = Array("KeepBackgroundRemoval", "Keep Background Removal")
    result(345) = Array("LabelInsert", "Label Insert")
    result(346) = Array("LanguagePreferences", "Language Preferences")
    result(347) = Array("LaunchFormatBackground", "Launch Format Background")
    result(348) = Array("LearnAboutRecord", "Learn About Record")
    result(349) = Array("LeaveReader", "Leave Reader")
    result(350) = Array("LineStylesDialog", "Line Styles Dialog")
    result(351) = Array("LinkBreak", "Link Break")
    result(352) = Array("LinkChange", "Link Change")
    result(353) = Array("LinksUpdate", "Links Update")
    result(354) = Array("LinkToSlide", "Link To Slide")
    result(355) = Array("LockObject", "Lock Object")
    result(356) = Array("MacroPlay", "Macro Play")
    result(357) = Array("MacroSecurity", "Macro Security")
    result(358) = Array("MakeSegmentCurved", "Make Segment Curved")
    result(359) = Array("MakeSegmentStraight", "Make Segment Straight")

    ' Chunk 19 (commands 360-379)
    result(360) = Array("ManagePrivacy", "Manage Privacy")
    result(361) = Array("MarkAllRevTrackHighlightsAsRead", "Mark All Rev Track Highlights As Read")
    result(362) = Array("MarkAsDecorative", "Mark As Decorative")
    result(363) = Array("MasterViewClose", "Master View Close")
    result(364) = Array("MathInputEditor", "Math Input Editor")
    result(365) = Array("MediaPlayPreview", "Media Play Preview")
    result(366) = Array("MediaUpgrade", "Media Upgrade")
    result(367) = Array("MergeCells", "Merge Cells")
    result(368) = Array("MergeViewClose", "Merge View Close")
    result(369) = Array("MoreControlsDialog", "More Controls Dialog")
    result(370) = Array("MoreCorrectionAlternatives", "More Correction Alternatives")
    result(371) = Array("MoreLines2", "More Lines 2")
    result(372) = Array("MoreTextureOptions", "More Texture Options")
    result(373) = Array("MoveDocument", "Move Document")
    result(374) = Array("MovieFromClipOrganizerInsert", "Movie From Clip Organizer Insert")
    result(375) = Array("MovieFromFileInsert", "Movie From File Insert")
    result(376) = Array("MovieFromFileRecordingAutoPlay", "Movie From File Recording Auto Play")
    result(377) = Array("MoviePlay", "Movie Play")
    result(378) = Array("MSPPTInsertTableofContents", "MSPPT Insert Tableof Contents")
    result(379) = Array("MSPPTOpenSectionLink", "MSPPT Open Section Link")

    ' Chunk 20 (commands 380-399)
    result(380) = Array("NextPane", "Next Pane")
    result(381) = Array("NumberInsert", "Number Insert")
    result(382) = Array("ObjectAddText", "Object Add Text")
    result(383) = Array("ObjectBorderOutlineColorMoreColorsDialog", "Object Border Outline Color More Colors Dialog")
    result(384) = Array("ObjectBringForward", "Object Bring Forward")
    result(385) = Array("ObjectBringToFront", "Object Bring To Front")
    result(386) = Array("ObjectEditText", "Object Edit Text")
    result(387) = Array("ObjectFillMoreColorsDialog", "Object Fill More Colors Dialog")
    result(388) = Array("ObjectFlipHorizontal", "Object Flip Horizontal")
    result(389) = Array("ObjectFlipVertical", "Object Flip Vertical")
    result(390) = Array("ObjectFormatDialog", "Object Format Dialog")
    result(391) = Array("ObjectNudgeDown", "Object Nudge Down")
    result(392) = Array("ObjectNudgeLeft", "Object Nudge Left")
    result(393) = Array("ObjectNudgeRight", "Object Nudge Right")
    result(394) = Array("ObjectNudgeUp", "Object Nudge Up")
    result(395) = Array("ObjectPictureFill", "Object Picture Fill")
    result(396) = Array("ObjectRotateFree", "Object Rotate Free")
    result(397) = Array("ObjectRotateLeft90", "Object Rotate Left 90")
    result(398) = Array("ObjectRotateRight90", "Object Rotate Right 90")
    result(399) = Array("ObjectRotationOptionsDialog", "Object Rotation Options Dialog")

    ' Chunk 21 (commands 400-419)
    result(400) = Array("ObjectsAlignBottomSmart", "Objects Align Bottom Smart")
    result(401) = Array("ObjectsAlignCenterHorizontalSmart", "Objects Align Center Horizontal Smart")
    result(402) = Array("ObjectsAlignLeftSmart", "Objects Align Left Smart")
    result(403) = Array("ObjectsAlignMiddleVerticalSmart", "Objects Align Middle Vertical Smart")
    result(404) = Array("ObjectsAlignRightSmart", "Objects Align Right Smart")
    result(405) = Array("ObjectsAlignTopSmart", "Objects Align Top Smart")
    result(406) = Array("ObjectSaveAsPicture", "Object Save As Picture")
    result(407) = Array("ObjectSaveMedia", "Object Save Media")
    result(408) = Array("ObjectScreenRecording", "Object Screen Recording")
    result(409) = Array("ObjectScreenRecordingAutoPlay", "Object Screen Recording Auto Play")
    result(410) = Array("ObjectSendBackward", "Object Send Backward")
    result(411) = Array("ObjectSendToBack", "Object Send To Back")
    result(412) = Array("ObjectSetShapeDefaults", "Object Set Shape Defaults")
    result(413) = Array("ObjectsGroup", "Objects Group")
    result(414) = Array("ObjectSizeAndPositionDialog", "Object Size And Position Dialog")
    result(415) = Array("ObjectSizeAndPropertiesDialog", "Object Size And Properties Dialog")
    result(416) = Array("ObjectsMultiSelect", "Objects Multi Select")
    result(417) = Array("ObjectsRegroup", "Objects Regroup")
    result(418) = Array("ObjectsUngroup", "Objects Ungroup")
    result(419) = Array("OfficeExtensionsAppStore", "Office Extensions App Store")

    ' Chunk 22 (commands 420-439)
    result(420) = Array("OfficeExtensionsDialog", "Office Extensions Dialog")
    result(421) = Array("OfficeExtensionsFeaturedApp1", "Office Extensions Featured App 1")
    result(422) = Array("OfficeExtensionsFeaturedApp2", "Office Extensions Featured App 2")
    result(423) = Array("OfficeExtensionsFeaturedApp3", "Office Extensions Featured App 3")
    result(424) = Array("OfficeExtensionsFeaturedApp4", "Office Extensions Featured App 4")
    result(425) = Array("OfficeExtensionsFeaturedApp5", "Office Extensions Featured App 5")
    result(426) = Array("OfficeExtensionsFeaturedApp6", "Office Extensions Featured App 6")
    result(427) = Array("OfficeExtensionsGallery3", "Office Extensions Gallery 3")
    result(428) = Array("OfficeExtensionsGetAddinsButtonOnBackstageBelowOpenDivider", "Office Extensions Get Addins Button On Backstage Below Open Divider")
    result(429) = Array("OfficeExtensionsManageOtherAddins", "Office Extensions Manage Other Addins")
    result(430) = Array("OfficeExtensionsShowAddinFlyout", "Office Extensions Show Addin Flyout")
    result(431) = Array("OfficeFeedback", "Office Feedback")
    result(432) = Array("OfficeFeedbackBackstage", "Office Feedback Backstage")
    result(433) = Array("OfficeFeedbackHelpTab", "Office Feedback Help Tab")
    result(434) = Array("OfficeFeedbackIcon", "Office Feedback Icon")
    result(435) = Array("OleConvert", "Ole Convert")
    result(436) = Array("OleObjectctInsert", "Ole Objectct Insert")
    result(437) = Array("OpenDefaultNative", "Open Default Native")
    result(438) = Array("OpenDefaultWeb", "Open Default Web")
    result(439) = Array("OpenMeetingNotes", "Open Meeting Notes")

    ' Chunk 23 (commands 440-459)
    result(440) = Array("OpenOptionsAddIns", "Open Options Add Ins")
    result(441) = Array("OpenOptionsAdvanced", "Open Options Advanced")
    result(442) = Array("OpenOptionsCustomization", "Open Options Customization")
    result(443) = Array("OpenOptionsCustomizeRibbon", "Open Options Customize Ribbon")
    result(444) = Array("OpenOptionsEaseOfAcess", "Open Options Ease Of Acess")
    result(445) = Array("OpenOptionsExperimentSettings", "Open Options Experiment Settings")
    result(446) = Array("OpenOptionsLanguage", "Open Options Language")
    result(447) = Array("OpenOptionsPPTTrustCenter", "Open Options PPT Trust Center")
    result(448) = Array("OpenOptionsSaving", "Open Options Saving")
    result(449) = Array("OpenOptionsSetup", "Open Options Setup")
    result(450) = Array("OpenOptionsSpelling", "Open Options Spelling")
    result(451) = Array("OpenOptionsTrustCenterSettings", "Open Options Trust Center Settings")
    result(452) = Array("OutlineCollapse", "Outline Collapse")
    result(453) = Array("OutlineDemote", "Outline Demote")
    result(454) = Array("OutlineExpand", "Outline Expand")
    result(455) = Array("OutlineExpandAll", "Outline Expand All")
    result(456) = Array("OutlineMoveDown", "Outline Move Down")
    result(457) = Array("OutlineMoveUp", "Outline Move Up")
    result(458) = Array("OutlinePromote", "Outline Promote")
    result(459) = Array("OutlineThumbnailsShowHide", "Outline Thumbnails Show Hide")

    ' Chunk 24 (commands 460-479)
    result(460) = Array("OutlookTaskCreate", "Outlook Task Create")
    result(461) = Array("PageNext", "Page Next")
    result(462) = Array("PagePrevious", "Page Previous")
    result(463) = Array("ParagraphDialog", "Paragraph Dialog")
    result(464) = Array("ParagraphMoreColumnsDialog", "Paragraph More Columns Dialog")
    result(465) = Array("Paste", "Paste")
    result(466) = Array("PasteApplyStyle", "Paste Apply Style")
    result(467) = Array("PasteAsEmbedded", "Paste As Embedded")
    result(468) = Array("PasteAsHyperlink", "Paste As Hyperlink")
    result(469) = Array("PasteAsPicture", "Paste As Picture")
    result(470) = Array("PasteAsSlide", "Paste As Slide")
    result(471) = Array("PasteBitmap", "Paste Bitmap")
    result(472) = Array("PasteDestinationTheme", "Paste Destination Theme")
    result(473) = Array("PasteDuplicate", "Paste Duplicate")
    result(474) = Array("PasteExcelChartDestinationTheme", "Paste Excel Chart Destination Theme")
    result(475) = Array("PasteExcelChartSourceFormatting", "Paste Excel Chart Source Formatting")
    result(476) = Array("PasteExcelTableDestinationTableStyle", "Paste Excel Table Destination Table Style")
    result(477) = Array("PasteExcelTableSourceFormatting", "Paste Excel Table Source Formatting")
    result(478) = Array("PasteGif", "Paste Gif")
    result(479) = Array("PasteInk", "Paste Ink")

    ' Chunk 25 (commands 480-499)
    result(480) = Array("PasteJpeg", "Paste Jpeg")
    result(481) = Array("PasteLinkedExcelChartDestinationTheme", "Paste Linked Excel Chart Destination Theme")
    result(482) = Array("PasteLinkedExcelChartSourceFormatting", "Paste Linked Excel Chart Source Formatting")
    result(483) = Array("PastePng", "Paste Png")
    result(484) = Array("PasteSourceFormatting", "Paste Source Formatting")
    result(485) = Array("PasteSpecialDialog", "Paste Special Dialog")
    result(486) = Array("PasteTextOnly", "Paste Text Only")
    result(487) = Array("PenAddFavorite", "Pen Add Favorite")
    result(488) = Array("PenAndInkHelp", "Pen And Ink Help")
    result(489) = Array("PhotoAlbumEdit", "Photo Album Edit")
    result(490) = Array("PhotoAlbumInsert", "Photo Album Insert")
    result(491) = Array("PickUpStyle", "Pick Up Style")
    result(492) = Array("PictureArtisticEffectsReset", "Picture Artistic Effects Reset")
    result(493) = Array("PictureAttributionNavigateToSource", "Picture Attribution Navigate To Source")
    result(494) = Array("PictureChange", "Picture Change")
    result(495) = Array("PictureChangeFromClipboard", "Picture Change From Clipboard")
    result(496) = Array("PictureChangeFromFile", "Picture Change From File")
    result(497) = Array("PictureChangeFromM365", "Picture Change From M 365")
    result(498) = Array("PictureChangeFromMobile", "Picture Change From Mobile")
    result(499) = Array("PictureChangeFromOnline", "Picture Change From Online")

    ' Chunk 26 (commands 500-519)
    result(500) = Array("PictureColorDialog", "Picture Color Dialog")
    result(501) = Array("PictureColorReset", "Picture Color Reset")
    result(502) = Array("PictureCorrectionsDialog", "Picture Corrections Dialog")
    result(503) = Array("PictureCorrectionsReset", "Picture Corrections Reset")
    result(504) = Array("PictureCropAspectRatio16To10", "Picture Crop Aspect Ratio 16 To 10")
    result(505) = Array("PictureCropAspectRatio16To9", "Picture Crop Aspect Ratio 16 To 9")
    result(506) = Array("PictureCropAspectRatio1To1", "Picture Crop Aspect Ratio 1 To 1")
    result(507) = Array("PictureCropAspectRatio2To3", "Picture Crop Aspect Ratio 2 To 3")
    result(508) = Array("PictureCropAspectRatio3To2", "Picture Crop Aspect Ratio 3 To 2")
    result(509) = Array("PictureCropAspectRatio3To4", "Picture Crop Aspect Ratio 3 To 4")
    result(510) = Array("PictureCropAspectRatio3To5", "Picture Crop Aspect Ratio 3 To 5")
    result(511) = Array("PictureCropAspectRatio4To3", "Picture Crop Aspect Ratio 4 To 3")
    result(512) = Array("PictureCropAspectRatio4To5", "Picture Crop Aspect Ratio 4 To 5")
    result(513) = Array("PictureCropAspectRatio5To3", "Picture Crop Aspect Ratio 5 To 3")
    result(514) = Array("PictureCropAspectRatio5To4", "Picture Crop Aspect Ratio 5 To 4")
    result(515) = Array("PictureEdit", "Picture Edit")
    result(516) = Array("PictureFillCrop", "Picture Fill Crop")
    result(517) = Array("PictureFitCrop", "Picture Fit Crop")
    result(518) = Array("PictureInsertFromFile", "Picture Insert From File")
    result(519) = Array("PictureInsertFromFilePowerPoint", "Picture Insert From File Power Point")

    ' Chunk 27 (commands 520-539)
    result(520) = Array("PictureMoreTransparency", "Picture More Transparency")
    result(521) = Array("PictureRecolorMoreColorsDialog", "Picture Recolor More Colors Dialog")
    result(522) = Array("PictureReset", "Picture Reset")
    result(523) = Array("PictureResetAndSize", "Picture Reset And Size")
    result(524) = Array("PicturesCompress", "Pictures Compress")
    result(525) = Array("PlaybackTipPlay", "Playback Tip Play")
    result(526) = Array("PodiumCloneSlideShow", "Podium Clone Slide Show")
    result(527) = Array("PodiumRecordSlideshowShortcutGuide", "Podium Record Slideshow Shortcut Guide")
    result(528) = Array("PodiumRecordSlideshowTeachingTour", "Podium Record Slideshow Teaching Tour")
    result(529) = Array("PodiumRetakeOnAllSlides", "Podium Retake On All Slides")
    result(530) = Array("PodiumRetakeOnCurrentSlide", "Podium Retake On Current Slide")
    result(531) = Array("PodiumSwitchMonitors", "Podium Switch Monitors")
    result(532) = Array("PresentInTeamsMeeting", "Present In Teams Meeting")
    result(533) = Array("PreviewRecordedVideo", "Preview Recorded Video")
    result(534) = Array("PrintPreviewAndPrint", "Print Preview And Print")
    result(535) = Array("PrintPreviewClose", "Print Preview Close")
    result(536) = Array("PropertySheet", "Property Sheet")
    result(537) = Array("QuickAccessToolbarCustomization", "Quick Access Toolbar Customization")
    result(538) = Array("RecordNarration", "Record Narration")
    result(539) = Array("RecordNarrationFromCurrentSlide", "Record Narration From Current Slide")

    ' Chunk 28 (commands 540-559)
    result(540) = Array("RedoOrRepeat", "Redo Or Repeat")
    result(541) = Array("ReflectionsMoreOptions", "Reflections More Options")
    result(542) = Array("RefreshServerFile", "Refresh Server File")
    result(543) = Array("Rehearse", "Rehearse")
    result(544) = Array("RemoveClosedCaption", "Remove Closed Caption")
    result(545) = Array("ReopenFromServer", "Reopen From Server")
    result(546) = Array("ReopenServerFile", "Reopen Server File")
    result(547) = Array("ReplaceDialog", "Replace Dialog")
    result(548) = Array("Reset3DModel", "Reset 3 D Model")
    result(549) = Array("Reset3DModelAndSize", "Reset 3 D Model And Size")
    result(550) = Array("ResetLayout", "Reset Layout")
    result(551) = Array("ResetToCameoOnAllSlides", "Reset To Cameo On All Slides")
    result(552) = Array("ResetToCameoOnCurrentSlide", "Reset To Cameo On Current Slide")
    result(553) = Array("ReviewCompareAndMerge", "Review Compare And Merge")
    result(554) = Array("ReviewDeleteAllMarkupInPresentation", "Review Delete All Markup In Presentation")
    result(555) = Array("ReviewDeleteAllMarkupOnSlide", "Review Delete All Markup On Slide")
    result(556) = Array("ReviewDeleteCommentPowerPoint", "Review Delete Comment Power Point")
    result(557) = Array("ReviewEditComment", "Review Edit Comment")
    result(558) = Array("ReviewEndReviewPowerPoint", "Review End Review Power Point")
    result(559) = Array("ReviewNewComment", "Review New Comment")

    ' Chunk 29 (commands 560-579)
    result(560) = Array("ReviewNextChange", "Review Next Change")
    result(561) = Array("ReviewNextCommentPowerPoint", "Review Next Comment Power Point")
    result(562) = Array("ReviewPresentationRevisionAccept", "Review Presentation Revision Accept")
    result(563) = Array("ReviewPresentationRevisionReject", "Review Presentation Revision Reject")
    result(564) = Array("ReviewPreviousChange", "Review Previous Change")
    result(565) = Array("ReviewPreviousCommentPowerPoint", "Review Previous Comment Power Point")
    result(566) = Array("ReviewRevisionAccept", "Review Revision Accept")
    result(567) = Array("ReviewRevisionReject", "Review Revision Reject")
    result(568) = Array("ReviewSlideRevisionAccept", "Review Slide Revision Accept")
    result(569) = Array("ReviewSlideRevisionReject", "Review Slide Revision Reject")
    result(570) = Array("RibbonCustomization", "Ribbon Customization")
    result(571) = Array("SaveAndReview", "Save And Review")
    result(572) = Array("ScreenClipping", "Screen Clipping")
    result(573) = Array("SecondCorrectionAlternative", "Second Correction Alternative")
    result(574) = Array("SectionAdd", "Section Add")
    result(575) = Array("SectionCollapseAll", "Section Collapse All")
    result(576) = Array("SectionDelete", "Section Delete")
    result(577) = Array("SectionExpandAll", "Section Expand All")
    result(578) = Array("SectionMergeWithPrevious", "Section Merge With Previous")
    result(579) = Array("SectionMoveDown", "Section Move Down")

    ' Chunk 30 (commands 580-599)
    result(580) = Array("SectionMoveUp", "Section Move Up")
    result(581) = Array("SectionRemoveAll", "Section Remove All")
    result(582) = Array("SectionRename", "Section Rename")
    result(583) = Array("SectionZoomInsert", "Section Zoom Insert")
    result(584) = Array("SelectAll", "Select All")
    result(585) = Array("SelectionToMathConvert", "Selection To Math Convert")
    result(586) = Array("SetAsSlideTitle", "Set As Slide Title")
    result(587) = Array("SetLanguage", "Set Language")
    result(588) = Array("ShadowNudgeDownClassic", "Shadow Nudge Down Classic")
    result(589) = Array("ShadowNudgeLeftClassic", "Shadow Nudge Left Classic")
    result(590) = Array("ShadowNudgeRightClassic", "Shadow Nudge Right Classic")
    result(591) = Array("ShadowNudgeUpClassic", "Shadow Nudge Up Classic")
    result(592) = Array("ShadowOnOrOffClassic", "Shadow On Or Off Classic")
    result(593) = Array("ShadowOptionsDialog", "Shadow Options Dialog")
    result(594) = Array("ShapeConvertToFreeform", "Shape Convert To Freeform")
    result(595) = Array("ShapeFillMoreGradientsDialog", "Shape Fill More Gradients Dialog")
    result(596) = Array("ShapesCombine", "Shapes Combine")
    result(597) = Array("ShapesFragment", "Shapes Fragment")
    result(598) = Array("ShapesIntersect", "Shapes Intersect")
    result(599) = Array("ShapesMoreShapes", "Shapes More Shapes")

    ' Chunk 31 (commands 600-619)
    result(600) = Array("ShapesSubtract", "Shapes Subtract")
    result(601) = Array("ShapesUnion", "Shapes Union")
    result(602) = Array("ShareDocument", "Share Document")
    result(603) = Array("ShareNotesWithMeeting", "Share Notes With Meeting")
    result(604) = Array("ShowTraining", "Show Training")
    result(605) = Array("SlideBackgroundFormatDialog", "Slide Background Format Dialog")
    result(606) = Array("SlideBackgroundReset", "Slide Background Reset")
    result(607) = Array("SlideDelete", "Slide Delete")
    result(608) = Array("SlideLinkReset", "Slide Link Reset")
    result(609) = Array("SlideMasterChartPlaceholderInsert", "Slide Master Chart Placeholder Insert")
    result(610) = Array("SlideMasterClipArtPlaceholderInsert", "Slide Master Clip Art Placeholder Insert")
    result(611) = Array("SlideMasterContentPlaceholderInsert", "Slide Master Content Placeholder Insert")
    result(612) = Array("SlideMasterDiagramPlaceholderInsert", "Slide Master Diagram Placeholder Insert")
    result(613) = Array("SlideMasterInsertLayout", "Slide Master Insert Layout")
    result(614) = Array("SlideMasterMasterLayout", "Slide Master Master Layout")
    result(615) = Array("SlideMasterMediaPlaceholderInsert", "Slide Master Media Placeholder Insert")
    result(616) = Array("SlideMasterPicturePlaceholderInsert", "Slide Master Picture Placeholder Insert")
    result(617) = Array("SlideMasterRenameMaster", "Slide Master Rename Master")
    result(618) = Array("SlideMasterTablePlaceholderInsert", "Slide Master Table Placeholder Insert")
    result(619) = Array("SlideMasterTextPlaceholderInsert", "Slide Master Text Placeholder Insert")

    ' Chunk 32 (commands 620-639)
    result(620) = Array("SlideMasterVerticalContentPlaceholderInsert", "Slide Master Vertical Content Placeholder Insert")
    result(621) = Array("SlideMasterVerticalTextPlaceholderInsert", "Slide Master Vertical Text Placeholder Insert")
    result(622) = Array("SlideNew", "Slide New")
    result(623) = Array("SlideReset", "Slide Reset")
    result(624) = Array("SlidesFromOutline", "Slides From Outline")
    result(625) = Array("SlideShowClearAllSlidesNarrations", "Slide Show Clear All Slides Narrations")
    result(626) = Array("SlideShowClearAllSlidesTimings", "Slide Show Clear All Slides Timings")
    result(627) = Array("SlideShowClearCurrentSlideNarration", "Slide Show Clear Current Slide Narration")
    result(628) = Array("SlideShowClearCurrentSlideTiming", "Slide Show Clear Current Slide Timing")
    result(629) = Array("SlideShowCustom", "Slide Show Custom")
    result(630) = Array("SlideShowFromBeginning", "Slide Show From Beginning")
    result(631) = Array("SlideShowFromCurrent", "Slide Show From Current")
    result(632) = Array("SlideShowInAWindow", "Slide Show In A Window")
    result(633) = Array("SlideShowNextSlide", "Slide Show Next Slide")
    result(634) = Array("SlideShowPreviousSlide", "Slide Show Previous Slide")
    result(635) = Array("SlideShowRehearseTimings", "Slide Show Rehearse Timings")
    result(636) = Array("SlideShowResumeShow", "Slide Show Resume Show")
    result(637) = Array("SlideShowSetUpDialog", "Slide Show Set Up Dialog")
    result(638) = Array("SlideTitleDefault", "Slide Title Default")
    result(639) = Array("SlideTransitionApplyToAll", "Slide Transition Apply To All")

    ' Chunk 33 (commands 640-659)
    result(640) = Array("SlideZoomInsert", "Slide Zoom Insert")
    result(641) = Array("SmartArtAddAssistant", "Smart Art Add Assistant")
    result(642) = Array("SmartArtAddBullet", "Smart Art Add Bullet")
    result(643) = Array("SmartArtAddShape", "Smart Art Add Shape")
    result(644) = Array("SmartArtAddShapeAbove", "Smart Art Add Shape Above")
    result(645) = Array("SmartArtAddShapeAfter", "Smart Art Add Shape After")
    result(646) = Array("SmartArtAddShapeBefore", "Smart Art Add Shape Before")
    result(647) = Array("SmartArtAddShapeBelow", "Smart Art Add Shape Below")
    result(648) = Array("SmartArtChangeLayout", "Smart Art Change Layout")
    result(649) = Array("SmartArtConvedrtToText", "Smart Art Convedrt To Text")
    result(650) = Array("SmartArtConvertToShapes", "Smart Art Convert To Shapes")
    result(651) = Array("SmartArtDemote", "Smart Art Demote")
    result(652) = Array("SmartArtInsert", "Smart Art Insert")
    result(653) = Array("SmartArtLargerShape", "Smart Art Larger Shape")
    result(654) = Array("SmartArtMoreLayoutsDialog", "Smart Art More Layouts Dialog")
    result(655) = Array("SmartArtOrganizationChartBoth", "Smart Art Organization Chart Both")
    result(656) = Array("SmartArtOrganizationChartLeftHanging", "Smart Art Organization Chart Left Hanging")
    result(657) = Array("SmartArtOrganizationChartRightHanging", "Smart Art Organization Chart Right Hanging")
    result(658) = Array("SmartArtOrganizationChartStandard", "Smart Art Organization Chart Standard")
    result(659) = Array("SmartArtPromote", "Smart Art Promote")

    ' Chunk 34 (commands 660-679)
    result(660) = Array("SmartArtReorderDown", "Smart Art Reorder Down")
    result(661) = Array("SmartArtReorderUp", "Smart Art Reorder Up")
    result(662) = Array("SmartArtResetGraphic", "Smart Art Reset Graphic")
    result(663) = Array("SmartArtResetShape", "Smart Art Reset Shape")
    result(664) = Array("SmartArtSmallerShape", "Smart Art Smaller Shape")
    result(665) = Array("SmartTagOptions", "Smart Tag Options")
    result(666) = Array("SoftEdgesMoreOptions", "Soft Edges More Options")
    result(667) = Array("SoundInsertFromClipOrganizer", "Sound Insert From Clip Organizer")
    result(668) = Array("SoundInsertFromFile", "Sound Insert From File")
    result(669) = Array("SoundInsertFromFileAutoPlay", "Sound Insert From File Auto Play")
    result(670) = Array("SoundRecord", "Sound Record")
    result(671) = Array("SoundRecordAutoPlay", "Sound Record Auto Play")
    result(672) = Array("Spelling", "Spelling")
    result(673) = Array("SplitCells", "Split Cells")
    result(674) = Array("SubtitleMoreSettings", "Subtitle More Settings")
    result(675) = Array("SVGEdit", "SVG Edit")
    result(676) = Array("SymbolInsert", "Symbol Insert")
    result(677) = Array("TableBackgroundPictureFill", "Table Background Picture Fill")
    result(678) = Array("TableBorderColorMoreColorsDialog", "Table Border Color More Colors Dialog")
    result(679) = Array("TableCellCustomMarginsDialog", "Table Cell Custom Margins Dialog")

    ' Chunk 35 (commands 680-699)
    result(680) = Array("TableColumnsDistribute", "Table Columns Distribute")
    result(681) = Array("TableColumnSelect", "Table Column Select")
    result(682) = Array("TableDelete", "Table Delete")
    result(683) = Array("TableDeleteColumns", "Table Delete Columns")
    result(684) = Array("TableDeleteRows", "Table Delete Rows")
    result(685) = Array("TableFillColorMoreColorsDialog", "Table Fill Color More Colors Dialog")
    result(686) = Array("TableInsert", "Table Insert")
    result(687) = Array("TableInsertColumnsLeft", "Table Insert Columns Left")
    result(688) = Array("TableInsertColumnsRight", "Table Insert Columns Right")
    result(689) = Array("TableInsertDialog", "Table Insert Dialog")
    result(690) = Array("TableInsertRowsAbove", "Table Insert Rows Above")
    result(691) = Array("TableInsertRowsBelow", "Table Insert Rows Below")
    result(692) = Array("TableRowsDistribute", "Table Rows Distribute")
    result(693) = Array("TableRowSelect", "Table Row Select")
    result(694) = Array("TableSelect", "Table Select")
    result(695) = Array("TableStyleClearTable", "Table Style Clear Table")
    result(696) = Array("TextAlignMoreOptionsDialog", "Text Align More Options Dialog")
    result(697) = Array("TextDirectionMoreOptionsDialog", "Text Direction More Options Dialog")
    result(698) = Array("TextEditModeExit", "Text Edit Mode Exit")
    result(699) = Array("TextEffects3DRotationOptionsDialog", "Text Effects 3 D Rotation Options Dialog")

    ' Chunk 36 (commands 700-719)
    result(700) = Array("TextEffectsBevelMore3DOptionsDialog", "Text Effects Bevel More 3 D Options Dialog")
    result(701) = Array("TextEffectsGlowsMoreOptions", "Text Effects Glows More Options")
    result(702) = Array("TextEffectsMoreShadowsDialog", "Text Effects More Shadows Dialog")
    result(703) = Array("TextEffectsReflectionsMoreOptions", "Text Effects Reflections More Options")
    result(704) = Array("TextFillColorMoreColorsDialog", "Text Fill Color More Colors Dialog")
    result(705) = Array("TextFillMoreGradientsDialog", "Text Fill More Gradients Dialog")
    result(706) = Array("TextFillMoreTextures", "Text Fill More Textures")
    result(707) = Array("TextGlowColorMoreColorsDialog", "Text Glow Color More Colors Dialog")
    result(708) = Array("TextOutlineColorMoreColorsDialog", "Text Outline Color More Colors Dialog")
    result(709) = Array("TextOutlineMoreLinesDialog", "Text Outline More Lines Dialog")
    result(710) = Array("TextPictureFill", "Text Picture Fill")
    result(711) = Array("ThemeBrowseForThemesPowerPoint", "Theme Browse For Themes Power Point")
    result(712) = Array("ThemeColorsCreateNew", "Theme Colors Create New")
    result(713) = Array("ThemeColorsReset", "Theme Colors Reset")
    result(714) = Array("ThemeFontsCreateNew", "Theme Fonts Create New")
    result(715) = Array("ThemeSaveCurrentPowerPoint", "Theme Save Current Power Point")
    result(716) = Array("ThemeSearchOfficeOnlinePowerPoint", "Theme Search Office Online Power Point")
    result(717) = Array("Thesaurus", "Thesaurus")
    result(718) = Array("ThirdCorrectionAlternative", "Third Correction Alternative")
    result(719) = Array("TransitionByObject", "Transition By Object")

    ' Chunk 37 (commands 720-739)
    result(720) = Array("TransitionPreview", "Transition Preview")
    result(721) = Array("Translate", "Translate")
    result(722) = Array("TranslateSelected", "Translate Selected")
    result(723) = Array("TranslateToSimplifiedChinese", "Translate To Simplified Chinese")
    result(724) = Array("TranslateToTraditionalChinese", "Translate To Traditional Chinese")
    result(725) = Array("TranslationLanguageOptions", "Translation Language Options")
    result(726) = Array("Translator", "Translator")
    result(727) = Array("UnlockObject", "Unlock Object")
    result(728) = Array("UpdateChannel", "Update Channel")
    result(729) = Array("UpdateInteractiveIndex", "Update Interactive Index")
    result(730) = Array("UpgradeDocument", "Upgrade Document")
    result(731) = Array("UpgradePresentation", "Upgrade Presentation")
    result(732) = Array("UploadToMSStreamRecording", "Upload To MS Stream Recording")
    result(733) = Array("UsagePermissions", "Usage Permissions")
    result(734) = Array("VideoBookmarkAdd", "Video Bookmark Add")
    result(735) = Array("VideoBookmarkRemove", "Video Bookmark Remove")
    result(736) = Array("VideoColorDialog", "Video Color Dialog")
    result(737) = Array("VideoCorrectionsDialog", "Video Corrections Dialog")
    result(738) = Array("VideoDesignResetAndSize", "Video Design Reset And Size")
    result(739) = Array("VideoInsert", "Video Insert")

    ' Chunk 38 (commands 740-759)
    result(740) = Array("VideoInsertFromOnline", "Video Insert From Online")
    result(741) = Array("VideoPosterFrameCurrent", "Video Poster Frame Current")
    result(742) = Array("VideoPosterFrameFromFile", "Video Poster Frame From File")
    result(743) = Array("VideoPosterFrameReset", "Video Poster Frame Reset")
    result(744) = Array("VideoToolsDesignReset", "Video Tools Design Reset")
    result(745) = Array("VideoToolsTrim", "Video Tools Trim")
    result(746) = Array("ViewFullScreenView", "View Full Screen View")
    result(747) = Array("ViewSlideShowReadingView", "View Slide Show Reading View")
    result(748) = Array("ViewSlideShowView", "View Slide Show View")
    result(749) = Array("ViewVisualBasicCode", "View Visual Basic Code")
    result(750) = Array("VisualBasic", "Visual Basic")
    result(751) = Array("WebGoBack", "Web Go Back")
    result(752) = Array("WebGoForward", "Web Go Forward")
    result(753) = Array("WebOptionsDialog", "Web Options Dialog")
    result(754) = Array("WebPagePreview", "Web Page Preview")
    result(755) = Array("WhatsNewRecentUpdates", "Whats New Recent Updates")
    result(756) = Array("WindowClose", "Window Close")
    result(757) = Array("WindowFitToPage", "Window Fit To Page")
    result(758) = Array("WindowMinimize", "Window Minimize")
    result(759) = Array("WindowMoveSplit", "Window Move Split")

    ' Chunk 39 (commands 760-768)
    result(760) = Array("WindowNew", "Window New")
    result(761) = Array("WindowRestore", "Window Restore")
    result(762) = Array("WindowsArrangeAll", "Windows Arrange All")
    result(763) = Array("WindowsCascade", "Windows Cascade")
    result(764) = Array("WordArtClear", "Word Art Clear")
    result(765) = Array("WordArtFormatDialog", "Word Art Format Dialog")
    result(766) = Array("WordArtVerticalText", "Word Art Vertical Text")
    result(767) = Array("ZoomDialog", "Zoom Dialog")
    result(768) = Array("ZoomFitToWindow", "Zoom Fit To Window")

    GetAllCommands = result
End Function